import { Button, VerticalBox } from "std-widgets.slint";
import {TimerLabel, TimerInput} from "timer.slint";

import "./resources/font/FiraCode-Medium.ttf";

export component AppWindow inherits Window {
    //callback request-increase-value();

    callback button-pressed <=> timer.button-clicked;
    callback step();
    callback stop-timer();
    callback start-timer();
    callback play-sound();

    //in-out property<int> counter: 42;
    in-out property<string> timer_string: "Ready to Start";

    title: "Oxidoro Timer";
    icon: @image-url("resources/Oxidoro.png");
    padding: 10px;
    default-font-size: 12pt;
    default-font-family: "Fira Code";

    VerticalBox {
        // Text {
        //     text: "Counter: \{root.counter}";
        // }
        Button {
            text: "Test Sound";
            clicked => {
                root.play_sound();
            }
        }

        timer := TimerLabel {
            time: timer_string;   
        }
    }
}
