import { Button, VerticalBox } from "std-widgets.slint";

export enum TimerInput {
    Start,
    Stop,
    Step,
    Skip,
    Reset,
    Pause,
    Resume,
    Input,
}

export component TimerLabel {
    callback button-clicked(TimerInput);
    in property <string> time: "TEST";

    VerticalBox {  
        width: 100%;
        height: 100%;  
        GridLayout {
            Row {
                start := Button {
                    text: "Start Program";
                    clicked => {
                        button-clicked(TimerInput.Start);
                    }
                }
                stop := Button {
                    text: "Stop Program";
                    clicked => {
                        button-clicked(TimerInput.Stop);
                    }
                }
            }
        }

        Text {
            text: time;
            height: 50%;
            font-size: 32pt;
            vertical-alignment: center;
            horizontal-alignment: center;
        }

        input := Button {
            text: "input";
            width: 100%;
            clicked => {
                button-clicked(TimerInput.Input);
            }
        }
        GridLayout {
            Row {
                pause := Button {
                    text: "pause";
                    clicked => {
                        button-clicked(TimerInput.Pause);
                    }
                }
                resume := Button {
                    text: "resume";
                    clicked => {
                        button-clicked(TimerInput.Resume);
                    }
                }
                
                reset := Button {
                    text: "reset";
                    clicked => {
                        button-clicked(TimerInput.Reset);
                    }
                }
                skip := Button {
                    text: "skip";
                    clicked => {
                        button-clicked(TimerInput.Skip);
                    }
                }
            }
        }
    }
}