
import { Button, VerticalBox } from "std-widgets.slint";
export component TimerLabel {

    in property <string> time: "xx:xx";

    VerticalBox {    
        Text {
            text: time;
            font-size: 32pt;
            vertical-alignment: center;
            horizontal-alignment: center;
        }  
        GridLayout {
            Row {
                start := Button {
                    text: "start";
                    clicked => {

                    }
                }

                stop := Button {
                    text: "stop";
                    clicked => {

                    }
                }
                reset := Button {
                    text: "reset";
                    clicked => {

                    }
                }
                skip := Button {
                    text: "skip";
                    clicked => {

                    }
                }
            }
        }
    }
}